# Tiendanube
title: Tiendanube
email: support@tiendanube.com
description:
baseurl: ""
url: "https://tiendanube.github.io/about-our-product-team" 

collections: 
  playbook:
    output: true
    permalink: /:collection/:path