# Tiendanube
title: Tiendanube
email: support@tiendanube.com
description:
baseurl: "https://itbruno.github.io/product"
url: "https://itbruno.github.io/product" 

collections: 
  playbook:
    output: true
    permalink: /:collection/:path