# Tiendanube
title: Tiendanube
email: support@tiendanube.com
description:
baseurl: ""
url: "https://tiendanube.github.io/about"
company_url: "https://tiendanube.com"

collections: 
  about:
    output: true
    permalink: /:collection/:path
  books:
    output: true
    permalink: /:collection/:path

collections_dir: collections